default['remi']['file_name']  = 'remi-release-6.rpm'
default['remi']['remote_uri'] = 'http://rpms.famillecollet.com/enterprise/remi-release-6.rpm'
default['epel']['file_name']  = 'epel-release-6-8.noarch.rpm'
default['epel']['remote_uri'] = 'http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm'
default['php56']['timezone'] = 'Asia/Tokyo'
